networks:
  media_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  #####################
  ##    VPN tunnel   ##
  #####################

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WR_ADDRESS}
      - WIREGUARD_DNS=${WR_DNS}
      - SERVER_COUNTRIES=${SRV_COUNTIRES}
      - TZ=${TZ}
      - FIREWALL_VPN_INPUT_PORTS=8080,33844,8787,5030,5031,33845
      - HEALTH_SUCCESS_WAIT_DURATION=99999h
    volumes:
      - /opt/apps/gluetun:/gluetun
    ports:
      - "8080:8080" # qBittorrent Web UI
      - "33844:33844" # qBittorrent incoming TCP torrent port
      - "33844:33844/udp" # qBittorrent incoming UDP torrent port
      - "5030:5030" # slskd HTTP port
      - "5031:5031" # slskd HTTPS port self signed certificate
      - "33845:33845" # slskd incoming connections port
    networks:
      media_net:
        ipv4_address: 172.20.0.2
    restart: unless-stopped

  #####################
  ## File downloaders##
  #####################

  qbittorrent:
    image: qbittorrentofficial/qbittorrent-nox:latest
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /opt/apps/qbittorrent:/config
      - /mnt/media/downloads:/downloads
    restart: unless-stopped
    depends_on:
      - gluetun

  slskd:
    image: slskd/slskd
    network_mode: service:gluetun
    container_name: slskd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - /opt/apps/slskd:/app
      - /mnt/media/downloads/complete/music:/data/downloads
      - /mnt/media/downloads/incomplete:/data/incomplete_downloads
      - /mnt/media/library/music:/data/music
    restart: unless-stopped
    depends_on:
      - gluetun

  sabnzbd:
    image: ghcr.io/hotio/sabnzbd
    ports:
      - "8082:8082"
    environment:
      - WEBUI_PORTS=8082
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /opt/apps/sabnzbd/config:/config
      - /mnt/media/downloads:/data
    networks:
      media_net:
        ipv4_address: 172.20.0.3
    restart: unless-stopped

  #######################
  ## Files and metadata##
  ## searcher, indexer ##
  ## and mangement     ##
  #######################

  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    ports:
      - "5299:5299"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg
    volumes:
      - /opt/apps/lazylibrarian/data:/config
      - /mnt/media/downloads/:/downloads
      - /mnt/media/library/books:/books
      - /mnt/media/library/books/:/audiobooks
    networks:
      media_net:
        ipv4_address: 172.20.0.4
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /opt/apps/sonarr:/config
      - /mnt/media/downloads:/downloads
      - /mnt/media/library/tv:/tv
      - /mnt/media/library/anime-series:/anime
    networks:
      media_net:
        ipv4_address: 172.20.0.5
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /opt/apps/radarr:/config
      - /mnt/media/downloads:/downloads
      - /mnt/media/library/movies:/movies
      - /mnt/media/library/anime-movies:/anime
    networks:
      media_net:
        ipv4_address: 172.20.0.6
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /opt/apps/bazarr:/config
      - /mnt/media/library/movies:/movies
      - /mnt/media/library/tv:/tv
      - /mnt/media/library/anime-series:/anime-series
      - /mnt/media/library/anime-movies:/anime-movies
    networks:
      media_net:
        ipv4_address: 172.20.0.7
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /opt/apps/prowlarr:/config
    networks:
      media_net:
        ipv4_address: 172.20.0.8
    restart: unless-stopped

  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    ports:
      - "9705:9705"
    volumes:
      - /opt/apps/huntarr:/config
    environment:
      - TZ=${TZ}
    networks:
      media_net:
        ipv4_address: 172.20.0.9
    restart: always

  beets:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /opt/apps/beets/config:/config
      - /mnt/media/library/music:/music
      - /mnt/media/downloads/complete/music:/downloads
    ports:
      - 8337:8337
    networks:
      media_net:
        ipv4_address: 172.20.0.10
    restart: unless-stopped

  qbitmanage:
    image: ghcr.io/hotio/qbitmanage
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /opt/apps/qbitmanage/config:/config
      - /mnt/media/downloads:/downloads
    networks:
      media_net:
        ipv4_address: 172.20.0.11
    restart: unless-stopped
    depends_on:
      - qbittorrent

  #####################
  ## File transcoder ##
  #####################

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    ports:
      - "8265:8265" # Web UI
      - "8266:8266" # Node API
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false
      - auth=true
      - authSecretKey=
    volumes:
      - /opt/apps/tdarr/server:/app/server
      - /opt/apps/tdarr/config:/app/configs
      - /mnt/media/apps/tdarr/temp:/temp
      - /mnt/media/library:/media
    networks:
      media_net:
        ipv4_address: 172.20.0.12
    restart: unless-stopped

  #####################
  ##  Media players  ##
  #####################

  jellyseerr:
    image: ghcr.io/hotio/jellyseerr
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ= ${TZ}
    volumes:
      - /srv/apps/jellyseerr:/config
    networks:
      media_net:
        ipv4_address: 172.20.0.13
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    volumes:
      - /opt/apps/jellyfin/config:/config
      - /opt/apps/jellyfin/cache:/cache
      - /mnt/media/library/movies:/media/movies:ro
      - /mnt/media/library/tv:/media/tv:ro
      - /mnt/media/library/anime-series:/anime-series:ro
      - /mnt/media/library/anime-movies:/anime-movies:ro
      - /mnt/media/fonts:/usr/local/share/fonts/custom:ro
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      - "1900:1900/udp"
    environment:
      - TZ=${TZ}
    networks:
      media_net:
        ipv4_address: 172.20.0.14
    restart: unless-stopped

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - /opt/apps/calibre-web/data:/config
      - /mnt/media/library/books:/books
      - /mnt/media/library/audiobooks/:/audiobooks
    ports:
      - 8083:8083
    networks:
      media_net:
        ipv4_address: 172.20.0.15
    restart: unless-stopped

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - LC_ALL=it_IT.UTF-8
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /opt/apps/calibre/config:/config
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
    networks:
      media_net:
        ipv4_address: 172.20.0.16
    restart: unless-stopped

  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000
    ports:
      - "4533:4533"
    environment:
      - TZ=${TZ}
      - ND_LOGLEVEL=info
      - ND_SCANINTERVAL=1h
      - ND_SESSIONTIMEOUT=24h
    volumes:
      - "/opt/apps/navidrome:/data"
      - "/mnt/media/library/music:/music:ro"
    networks:
      media_net:
        ipv4_address: 172.20.0.17
    restart: unless-stopped

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/apps/homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_KEY}
    networks:
      media_net:
        ipv4_address: 172.20.0.18
    ports:
      - "7575:7575"

  #####################
  ##      Tools      ##
  #####################

  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - TZ=${TZ}
    networks:
      media_net:
        ipv4_address: 172.20.0.19
    restart: unless-stopped

  unpackerr:
    image: ghcr.io/hotio/unpackerr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /opt/apps/unpackerr:/config
      - /mnt/media/downloads:/data
    networks:
      media_net:
        ipv4_address: 172.20.0.20
    restart: unless-stopped

  #######################
  ## Containers updater##
  #######################

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
    command: --interval 3600 --cleanup
    restart: unless-stopped
